In [44]:
import numpy as np
import torchrl
import importlib
import custom_torchrl_env

/home/emil/pyenvs/build_mujoco/lib/python3.10/site-packages/torchrl/__init__.py:36: UserWarning: failed to set start method to spawn, and current start method for mp is fork.
  warn(


In [45]:
importlib.reload(custom_torchrl_env)

<module 'custom_torchrl_env' from '/home/emil/Development/custom_torchrl_env/custom_torchrl_env.py'>

In [46]:
env = custom_torchrl_env.RodentRunEnv(batch_size=(47,17))
torchrl.envs.utils.check_env_specs(env)
transEnv = torchrl.envs.TransformedEnv(
    env,
    torchrl.envs.Compose(
        # normalize observations
        torchrl.envs.ObservationNorm(in_keys=["observation"]),
        torchrl.envs.StepCounter(max_steps=5),
        torchrl.envs.RewardSum()
    ),
)
transEnv.transform[0].init_stats(num_iter=48, cat_dim=0, reduce_dim=tuple(range(len(env.batch_size)+1)))
torchrl.envs.utils.check_env_specs(transEnv)
rollout = transEnv.rollout(10, break_when_any_done=False)

/home/emil/Development/custom_torchrl_env/custom_torchrl_env.py:73: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:206.)
  observation = torch.from_numpy(np.array(self.simulation_pool.getState(), copy=False))
2024-04-08 11:07:59,437 [torchrl][INFO] check_env_specs succeeded!
2024-04-08 11:08:00,032 [torchrl][INFO] check_env_specs succeeded!


In [47]:
td = transEnv.reset()
for t in range(3):
    td["action"] = transEnv.rand_action()["action"]
    td_, td = transEnv.step_and_maybe_reset(td)
td["done"][..., ::2, :] = True
td = transEnv.maybe_reset(td)
td_, td = transEnv.step_and_maybe_reset(td)
#td_, td = transEnv.step_and_maybe_reset(td)
td["step_count"].squeeze()

tensor([[1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 

In [135]:
td["done"]

tensor([[[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False]],

        [[False],
         [False],
         [False],
         [False],
    

In [83]:
transEnv.done_spec

CompositeSpec(
    done: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    terminated: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    truncated: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete), device=cpu, shape=torch.Size([47]))

In [82]:
td_[("next", "step_count")]

tensor([[4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4]])

In [73]:
transEnv._simple_done

AttributeError: 'RodentRunEnv' object has no attribute '_simple_done'

In [55]:
transEnv.rand_action()["action"]

tensor([[-0.7168,  0.6856,  0.5460,  ..., -0.4156,  0.1290, -0.6670],
        [ 0.0838,  0.8155,  0.7097,  ...,  0.7834,  0.2277, -0.9487],
        [-0.3697,  0.9156,  0.6169,  ...,  0.8236, -0.6108,  0.1140],
        ...,
        [ 0.6618, -0.5534,  0.9632,  ...,  0.4257, -0.2014,  0.5587],
        [ 0.3576, -0.0321, -0.2948,  ..., -0.7316,  0.0589, -0.7645],
        [-0.0488,  0.3100, -0.0805,  ...,  0.7618, -0.2398,  0.8818]])

In [57]:
td#["action"]

(TensorDict(
     fields={
         action: Tensor(shape=torch.Size([47, 30]), device=cpu, dtype=torch.float32, is_shared=False),
         done: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.bool, is_shared=False),
         episode_reward: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.float32, is_shared=False),
         next: TensorDict(
             fields={
                 done: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                 episode_reward: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                 observation: Tensor(shape=torch.Size([47, 178]), device=cpu, dtype=torch.float32, is_shared=False),
                 reward: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                 step_count: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.int64, is_shared=False),
                 terminated: Tensor(shape=torch.Size

In [11]:
dmContEnv = torchrl.envs.DMControlEnv("humanoid", "stand")
batchDmContEnv = torchrl.envs.SerialEnv(7, lambda: torchrl.envs.DMControlEnv("humanoid", "stand"))

In [12]:
dmContEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([21]), device=cpu, dtype=torch.float64, is_shared=False),
        next: TensorDict(
            fields={
                com_velocity: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float64, is_shared=False),
                done: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.bool, is_shared=False),
                extremities: Tensor(shape=torch.Size([12]), device=cpu, dtype=torch.float64, is_shared=False),
                head_height: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.float64, is_shared=False),
                joint_angles: Tensor(shape=torch.Size([21]), device=cpu, dtype=torch.float64, is_shared=False),
                reward: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.float64, is_shared=False),
                terminated: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.bool, is_shared=False),
                torso_vertical: Tensor(shape=torch.Size([3]), device=cpu, d

In [13]:
batchDmContEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
        next: TensorDict(
            fields={
                com_velocity: Tensor(shape=torch.Size([7, 3]), device=cpu, dtype=torch.float64, is_shared=False),
                done: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                extremities: Tensor(shape=torch.Size([7, 12]), device=cpu, dtype=torch.float64, is_shared=False),
                head_height: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                joint_angles: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
                reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                terminated: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                torso_vertical: Tensor(shape=torch.

In [14]:
transBatchDmContEnv = torchrl.envs.TransformedEnv(
    batchDmContEnv,
    torchrl.envs.Compose(
        # normalize observations
        #torchrl.envs.ObservationNorm(in_keys=["observation"]),
        #torchrl.envs.StepCounter(max_steps=5),
        torchrl.envs.RewardSum()
    ),
)

In [15]:
transBatchDmContEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
        next: TensorDict(
            fields={
                com_velocity: Tensor(shape=torch.Size([7, 3]), device=cpu, dtype=torch.float64, is_shared=False),
                done: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                episode_reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                extremities: Tensor(shape=torch.Size([7, 12]), device=cpu, dtype=torch.float64, is_shared=False),
                head_height: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                joint_angles: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
                reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                terminated: Tensor(shape=tor

In [16]:
transBatchDmContEnv.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([7, 1]),
    space=None,
    device=cpu,
    dtype=torch.float64,
    domain=continuous)

In [17]:
batchDmContEnv.done_spec

CompositeSpec(
    done: DiscreteTensorSpec(
        shape=torch.Size([7, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    truncated: DiscreteTensorSpec(
        shape=torch.Size([7, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    terminated: DiscreteTensorSpec(
        shape=torch.Size([7, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete), device=cpu, shape=torch.Size([7]))

In [18]:
env.done_spec

CompositeSpec(
    done: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    terminated: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete), device=cpu, shape=torch.Size([47]))

In [19]:
env.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([47, 1]),
    space=None,
    device=cpu,
    dtype=torch.float32,
    domain=continuous)

In [20]:
batchDmContEnv.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([7, 1]),
    space=None,
    device=cpu,
    dtype=torch.float64,
    domain=continuous)

In [21]:
transBatchDmContEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
        next: TensorDict(
            fields={
                com_velocity: Tensor(shape=torch.Size([7, 3]), device=cpu, dtype=torch.float64, is_shared=False),
                done: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                episode_reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                extremities: Tensor(shape=torch.Size([7, 12]), device=cpu, dtype=torch.float64, is_shared=False),
                head_height: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                joint_angles: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
                reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                terminated: Tensor(shape=tor

In [22]:
transEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([47, 30]), device=cpu, dtype=torch.float32, is_shared=False),
        next: TensorDict(
            fields={
                done: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                episode_reward: Tensor(shape=torch.Size([47]), device=cpu, dtype=torch.float32, is_shared=False),
                observation: Tensor(shape=torch.Size([47, 178]), device=cpu, dtype=torch.float32, is_shared=False),
                reward: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                terminated: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.bool, is_shared=False)},
            batch_size=torch.Size([47]),
            device=cpu,
            is_shared=False)},
    batch_size=torch.Size([47]),
    device=cpu,
    is_shared=False)

In [23]:
batchDmContEnv.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([7, 1]),
    space=None,
    device=cpu,
    dtype=torch.float64,
    domain=continuous)

In [24]:
env.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([47, 1]),
    space=None,
    device=cpu,
    dtype=torch.float32,
    domain=continuous)

In [49]:
%time env.rollout(500)

CPU times: user 1min 35s, sys: 249 ms, total: 1min 35s
Wall time: 5.37 s


TensorDict(
    fields={
        action: Tensor(shape=torch.Size([47, 17, 500, 38]), device=cpu, dtype=torch.float32, is_shared=False),
        done: Tensor(shape=torch.Size([47, 17, 500, 1]), device=cpu, dtype=torch.bool, is_shared=False),
        next: TensorDict(
            fields={
                done: Tensor(shape=torch.Size([47, 17, 500, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                observation: Tensor(shape=torch.Size([47, 17, 500, 173]), device=cpu, dtype=torch.float32, is_shared=False),
                reward: Tensor(shape=torch.Size([47, 17, 500, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                terminated: Tensor(shape=torch.Size([47, 17, 500, 1]), device=cpu, dtype=torch.bool, is_shared=False)},
            batch_size=torch.Size([47, 17, 500]),
            device=None,
            is_shared=False),
        observation: Tensor(shape=torch.Size([47, 17, 500, 173]), device=cpu, dtype=torch.float32, is_shared=False),
        termin

In [50]:
47*17*500/5.37

74394.78584729982

# DMControl rodent model

In [28]:
import mujoco
import tqdm
import numpy as np
import mujoco._simulation_pool

In [6]:
model = mujoco.MjModel.from_xml_path("models/rodent_from_dm_control.xml")

In [7]:
data = mujoco.MjData(model)

In [26]:
mujoco.mj_resetData(model, data)
for t in tqdm.trange(10000):
    data.ctrl = np.random.uniform(-1, 1, model.nu)
    mujoco.mj_step(model, data, 10)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:11<00:00, 870.35it/s]


In [40]:
sm = mujoco._simulation_pool.SimulationPool(model, 64, 16, mujoco.mjtState.mjSTATE_FULLPHYSICS)

In [42]:
sm.reset(np.ones(64, bool))

In [43]:
for t in tqdm.trange(10000):
    sm.step()

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:08<00:00, 1226.82it/s]
