In [129]:
import numpy as np
import torchrl
import importlib
import custom_torchrl_env

In [130]:
importlib.reload(custom_torchrl_env)

<module 'custom_torchrl_env' from '/home/emil/Development/custom_torchrl_env/custom_torchrl_env.py'>

In [142]:
env = custom_torchrl_env.RodentRunEnv(batch_size=(47,17))
torchrl.envs.utils.check_env_specs(env)
transEnv = torchrl.envs.TransformedEnv(
    env,
    torchrl.envs.Compose(
        # normalize observations
        torchrl.envs.ObservationNorm(in_keys=["observation"]),
        torchrl.envs.StepCounter(max_steps=5),
        torchrl.envs.RewardSum()
    ),
)
transEnv.transform[0].init_stats(num_iter=48, cat_dim=0, reduce_dim=tuple(range(len(env.batch_size)+1)))
torchrl.envs.utils.check_env_specs(transEnv)
rollout = transEnv.rollout(10, break_when_any_done=False)

2024-04-05 17:32:03,362 [torchrl][INFO] check_env_specs succeeded!
2024-04-05 17:32:04,279 [torchrl][INFO] check_env_specs succeeded!


In [153]:
td = transEnv.reset()
for t in range(3):
    td["action"] = transEnv.rand_action()["action"]
    td_, td = transEnv.step_and_maybe_reset(td)
td["done"][..., ::2, :] = True
td = transEnv.maybe_reset(td)
td_, td = transEnv.step_and_maybe_reset(td)
#td_, td = transEnv.step_and_maybe_reset(td)
td["step_count"].squeeze()

tensor([[1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1, 4, 1],
        [1, 4, 1, 4, 1, 

In [135]:
td["done"]

tensor([[[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False]],

        [[False],
         [False],
         [False],
         [False],
    

In [83]:
transEnv.done_spec

CompositeSpec(
    done: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    terminated: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    truncated: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete), device=cpu, shape=torch.Size([47]))

In [82]:
td_[("next", "step_count")]

tensor([[4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4],
        [4]])

In [73]:
transEnv._simple_done

AttributeError: 'RodentRunEnv' object has no attribute '_simple_done'

In [55]:
transEnv.rand_action()["action"]

tensor([[-0.7168,  0.6856,  0.5460,  ..., -0.4156,  0.1290, -0.6670],
        [ 0.0838,  0.8155,  0.7097,  ...,  0.7834,  0.2277, -0.9487],
        [-0.3697,  0.9156,  0.6169,  ...,  0.8236, -0.6108,  0.1140],
        ...,
        [ 0.6618, -0.5534,  0.9632,  ...,  0.4257, -0.2014,  0.5587],
        [ 0.3576, -0.0321, -0.2948,  ..., -0.7316,  0.0589, -0.7645],
        [-0.0488,  0.3100, -0.0805,  ...,  0.7618, -0.2398,  0.8818]])

In [57]:
td#["action"]

(TensorDict(
     fields={
         action: Tensor(shape=torch.Size([47, 30]), device=cpu, dtype=torch.float32, is_shared=False),
         done: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.bool, is_shared=False),
         episode_reward: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.float32, is_shared=False),
         next: TensorDict(
             fields={
                 done: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                 episode_reward: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                 observation: Tensor(shape=torch.Size([47, 178]), device=cpu, dtype=torch.float32, is_shared=False),
                 reward: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                 step_count: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.int64, is_shared=False),
                 terminated: Tensor(shape=torch.Size

In [11]:
dmContEnv = torchrl.envs.DMControlEnv("humanoid", "stand")
batchDmContEnv = torchrl.envs.SerialEnv(7, lambda: torchrl.envs.DMControlEnv("humanoid", "stand"))

In [12]:
dmContEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([21]), device=cpu, dtype=torch.float64, is_shared=False),
        next: TensorDict(
            fields={
                com_velocity: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.float64, is_shared=False),
                done: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.bool, is_shared=False),
                extremities: Tensor(shape=torch.Size([12]), device=cpu, dtype=torch.float64, is_shared=False),
                head_height: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.float64, is_shared=False),
                joint_angles: Tensor(shape=torch.Size([21]), device=cpu, dtype=torch.float64, is_shared=False),
                reward: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.float64, is_shared=False),
                terminated: Tensor(shape=torch.Size([1]), device=cpu, dtype=torch.bool, is_shared=False),
                torso_vertical: Tensor(shape=torch.Size([3]), device=cpu, d

In [13]:
batchDmContEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
        next: TensorDict(
            fields={
                com_velocity: Tensor(shape=torch.Size([7, 3]), device=cpu, dtype=torch.float64, is_shared=False),
                done: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                extremities: Tensor(shape=torch.Size([7, 12]), device=cpu, dtype=torch.float64, is_shared=False),
                head_height: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                joint_angles: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
                reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                terminated: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                torso_vertical: Tensor(shape=torch.

In [14]:
transBatchDmContEnv = torchrl.envs.TransformedEnv(
    batchDmContEnv,
    torchrl.envs.Compose(
        # normalize observations
        #torchrl.envs.ObservationNorm(in_keys=["observation"]),
        #torchrl.envs.StepCounter(max_steps=5),
        torchrl.envs.RewardSum()
    ),
)

In [15]:
transBatchDmContEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
        next: TensorDict(
            fields={
                com_velocity: Tensor(shape=torch.Size([7, 3]), device=cpu, dtype=torch.float64, is_shared=False),
                done: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                episode_reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                extremities: Tensor(shape=torch.Size([7, 12]), device=cpu, dtype=torch.float64, is_shared=False),
                head_height: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                joint_angles: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
                reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                terminated: Tensor(shape=tor

In [16]:
transBatchDmContEnv.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([7, 1]),
    space=None,
    device=cpu,
    dtype=torch.float64,
    domain=continuous)

In [17]:
batchDmContEnv.done_spec

CompositeSpec(
    done: DiscreteTensorSpec(
        shape=torch.Size([7, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    truncated: DiscreteTensorSpec(
        shape=torch.Size([7, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    terminated: DiscreteTensorSpec(
        shape=torch.Size([7, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete), device=cpu, shape=torch.Size([7]))

In [18]:
env.done_spec

CompositeSpec(
    done: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete),
    terminated: DiscreteTensorSpec(
        shape=torch.Size([47, 1]),
        space=DiscreteBox(n=2),
        device=cpu,
        dtype=torch.bool,
        domain=discrete), device=cpu, shape=torch.Size([47]))

In [19]:
env.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([47, 1]),
    space=None,
    device=cpu,
    dtype=torch.float32,
    domain=continuous)

In [20]:
batchDmContEnv.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([7, 1]),
    space=None,
    device=cpu,
    dtype=torch.float64,
    domain=continuous)

In [21]:
transBatchDmContEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
        next: TensorDict(
            fields={
                com_velocity: Tensor(shape=torch.Size([7, 3]), device=cpu, dtype=torch.float64, is_shared=False),
                done: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                episode_reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                extremities: Tensor(shape=torch.Size([7, 12]), device=cpu, dtype=torch.float64, is_shared=False),
                head_height: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                joint_angles: Tensor(shape=torch.Size([7, 21]), device=cpu, dtype=torch.float64, is_shared=False),
                reward: Tensor(shape=torch.Size([7, 1]), device=cpu, dtype=torch.float64, is_shared=False),
                terminated: Tensor(shape=tor

In [22]:
transEnv.rand_step()

TensorDict(
    fields={
        action: Tensor(shape=torch.Size([47, 30]), device=cpu, dtype=torch.float32, is_shared=False),
        next: TensorDict(
            fields={
                done: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.bool, is_shared=False),
                episode_reward: Tensor(shape=torch.Size([47]), device=cpu, dtype=torch.float32, is_shared=False),
                observation: Tensor(shape=torch.Size([47, 178]), device=cpu, dtype=torch.float32, is_shared=False),
                reward: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                terminated: Tensor(shape=torch.Size([47, 1]), device=cpu, dtype=torch.bool, is_shared=False)},
            batch_size=torch.Size([47]),
            device=cpu,
            is_shared=False)},
    batch_size=torch.Size([47]),
    device=cpu,
    is_shared=False)

In [23]:
batchDmContEnv.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([7, 1]),
    space=None,
    device=cpu,
    dtype=torch.float64,
    domain=continuous)

In [24]:
env.reward_spec

UnboundedContinuousTensorSpec(
    shape=torch.Size([47, 1]),
    space=None,
    device=cpu,
    dtype=torch.float32,
    domain=continuous)